name: Custom_Framework
version: '1.0-SNAPSHOT'
main: CAZA.custom_Framework.Custom_Framework
api-version: '1.19'

commands:
  test:
    description: "Check if a this thing works or not"
    usage: /test