name: Custom_Framework
version: '1.0-SNAPSHOT'
main: com.zacharyvds.quillmc.Custom_Framework
api-version: '1.19'

commands:
  test:
    description: "Check if a this thing works or not"
    usage: /test
  pizza:
    description: "Return a random pizza flavor"
    usage: /pizza
  vst:
    descipriont: "Test for virtual servers"
    usage: /vst